## 创建Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ilab_demo
  name: ilab_demo
  namespace: ilab_demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ilab_demo
        track: stable
    spec:
      containers:
        - name: ilab_demo
          image: ilab_demo:v1
          ports:
            - containerPort: 8899
---
apiVersion: v1
kind: Service
metadata:
  name: ilab_demo
spec:
  type: NodePort
  selector:
    app: ilab_demo
  ports:
    - protocol: TCP
      port: 8899
      targetPort: 8899